{% set name = "gocart" %}
{% set version = "0.4.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 497ba8b85d3ca8094869644b712aa6265891505a3860adef33c3b48da425c736

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gocart = gocart.cl_utils:main

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - fundamentals
    - python >=3.9
    - pyyaml
    - astropy-base
    - astropy-healpix
    - numpy
    - matplotlib-base
    - healpy
    - pandas
    - tabulate
    - gcn-kafka
    - mhealpy

test:
  imports:
    - gocart

about:
  home: https://github.com/thespacedoctor/gocart
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Listen for, collect and convert multimessenger skymaps
  doc_url: https://gocart.readthedocs.io
  dev_url: https://github.com/thespacedoctor/gocart

extra:
  recipe-maintainers:
    - thespacedoctor
